// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinGo.Quartz.Platform.Data;

#nullable disable

namespace MinGo.Quartz.Platform.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260905221806_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MinGo.Quartz.Platform.Data.Entities.AgentInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeartbeatIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastHeartbeat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OfflineThresholdSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RegisteredAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningThresholdSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasFilter("TokenHash IS NOT NULL");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("MinGo.Quartz.Platform.Data.Entities.AgentScheduler", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ReportedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchedulerInfoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchedulerInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchedulerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SchedulerInfoId");

                    b.HasIndex("SchedulerName");

                    b.HasIndex("AgentId", "SchedulerName")
                        .IsUnique();

                    b.ToTable("AgentSchedulers", (string)null);
                });

            modelBuilder.Entity("MinGo.Quartz.Platform.Data.Entities.ExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomFieldsJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorType")
                        .HasColumnType("TEXT");

                    b.Property<string>("FireInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchedulerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.HasIndex("AgentId", "StartTime");

                    b.HasIndex("JobGroup", "JobName", "StartTime");

                    b.ToTable("ExecutionLogs", (string)null);
                });

            modelBuilder.Entity("MinGo.Quartz.Platform.Data.Entities.JobDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobGroup")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchedulerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggersJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SchedulerName", "JobGroup", "JobName")
                        .IsUnique();

                    b.ToTable("JobDefinitions", (string)null);
                });

            modelBuilder.Entity("MinGo.Quartz.Platform.Data.Entities.SchedulerInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstReportedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClustered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobCountsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobStoreType")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastReportedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfJobsExecuted")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RunningSince")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadPoolSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThreadPoolType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SchedulerInfos", (string)null);
                });

            modelBuilder.Entity("MinGo.Quartz.Platform.Data.Entities.AgentScheduler", b =>
                {
                    b.HasOne("MinGo.Quartz.Platform.Data.Entities.AgentInfo", "Agent")
                        .WithMany("Schedulers")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinGo.Quartz.Platform.Data.Entities.SchedulerInfo", null)
                        .WithMany("AgentSchedulers")
                        .HasForeignKey("SchedulerInfoId");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("MinGo.Quartz.Platform.Data.Entities.ExecutionLog", b =>
                {
                    b.HasOne("MinGo.Quartz.Platform.Data.Entities.AgentInfo", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("MinGo.Quartz.Platform.Data.Entities.AgentInfo", b =>
                {
                    b.Navigation("Schedulers");
                });

            modelBuilder.Entity("MinGo.Quartz.Platform.Data.Entities.SchedulerInfo", b =>
                {
                    b.Navigation("AgentSchedulers");
                });
#pragma warning restore 612, 618
        }
    }
}
